snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - skip: true

archives:
  - id: ste-helm
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}"
    wrap_in_directory: true
    meta: true
    files:
      - integrations/*
      - categraf/*
      - metrics/*
      - scripts/*
      - templates/*
      - tpl/*
      - Chart.yaml
      - LICENSE
      - ste-icon.png
      - README.md
      - README-CN.md
      - values.yaml

release:
  github:
    owner: caapap
    name: ste-helm
  name_template: "v{{ .Version }}"
