{{/*
# Copyright 2024 kxdigit | 讯飞数码
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
*/}}
{{- if eq .Values.expose.type "ingress" }}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
{{- if eq .Values.expose.ingress.controller "gce" }}
  {{- $_ := set . "root_path" "/*" -}}
{{- else if eq .Values.expose.ingress.controller "ncp" }}
  {{- $_ := set . "root_path" "/.*" -}}
{{- else }}
  {{- $_ := set . "root_path" "/" -}}
{{- end }}

---
{{- if semverCompare "<1.14-0" (include "stellar.ingress.kubeVersion" .) }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" (include "stellar.ingress.kubeVersion" .) }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: "{{ template "stellar.ingress" . }}"
  labels:
{{ include "stellar.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- if eq .Values.expose.ingress.controller "ncp" }}
    ncp/use-regex: "true"
    {{- if $tls.enabled }}
    ncp/http-redirect: "true"
    {{- end }}
{{- end }}
{{- if $ingress.stellar.annotations }}
{{ toYaml $ingress.stellar.annotations | indent 4 }}
{{- end }}
spec:
  {{- if $tls.enabled }}
  tls:
  - secretName: {{ template "stellar.tlsSecretForIngress" . }}
    {{- if $ingress.hosts.web }}
    hosts:
    - {{ $ingress.hosts.web }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
{{- if semverCompare "<1.19-0" (include "stellar.ingress.kubeVersion" .) }}
      - path: {{ .root_path }}
        backend:
          serviceName: {{ template "stellar.ste" . }}
          servicePort: {{ template "stellar.ste.servicePort" . }}
{{- else }}
      - path: {{ .root_path }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "stellar.ste" . }}
            port:
              number: {{ template "stellar.ste.servicePort" . }}
{{- end }}
    {{- if $ingress.hosts.web }}
    host: {{ $ingress.hosts.web }}
    {{- end }}
{{- end }}
